# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - catchmaster

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: "18.x"

            - name: npm install, build, and test
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                  GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
                  APP_URL: ${{ secrets.APP_URL }}
                  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
                  SESSION_COOKIE_NAME: ${{ secrets.SESSION_COOKIE_NAME }}
                  VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
              run: |
                  npm install -w server
                  npm run build -w server

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v2
              with:
                  name: node-app
                  path: .

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v2
              with:
                  name: node-app

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "catchmaster"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8C463144B4B943EC85F3BC2071BDF09C }}
                  package: .
